name: id_registry
description: A Dart package providing an registry for id_pair_sets.
version: 1.0.0
repository: https://github.com/staylorx/id_registry
issue_tracker: https://github.com/staylorx/id_registry/issues
documentation: https://github.com/staylorx/id_registry

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  id_pair_set: ^1.2.1
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
